- type: entity
  id: RMCRandomHumanoidCMBInformant
  name: CMB Informant
  suffix: Spawner, Informant
  components:
  - type: Sprite
    sprite: _RMC14/Structures/Machines/fax_machine.rsi
    state: icon
  - type: RandomHumanoidSpawner
    settings: RMCCMBInformantSettings

- type: randomHumanoidSettings
  parent: RMCEventHumanoid
  id: RMCCMBInformantSettings
  components:
  - type: Rank
    rank: RMCRankCivilian
  - type: Loadout
    prototypes: [ RMCGearCMBInformant  ]
  - type: GhostRole
    name: "CMB Informant"
    description: "You are a informant for the Colony Marshal Buero. Relay any happenings in the area to them via fax. Try not to let the public know. The GM probably has a specific job in mind..."
    rules: "You do not remember your previous life. You are NOT hostile to any faction unless directed to be by the GM or a admin. Try to blend in, and behave as a civilian colonist would."
    reregister: false
    raffle:
      settings: short
  - type: GhostRoleApplySpecial
  - type: Skills
    skills:
      RMCSkillConstruction: 1
      RMCSkillEndurance: 2
      RMCSkillFireman: 1
      RMCSkillFirearms: 1

- type: startingGear
  id: RMCGearCMBInformant
  equipment:
    jumpsuit: CMJumpsuitColonist
    back: RMCSatchelCMBInformantFill
    shoes: RMCShoesBlack
    id: RMCIDCardCMBInformantFakeID
    ears: CMHeadsetColony
    pocket1: RMCPouchSurvivalFill
    pocket2: RMCPouchGeneral

- type: entity
  parent: CMIDCardGold
  id: RMCIDCardCMBInformant
  name: "CMB Informant ID card"
  description: A shiny ID card, issued to the covert intelligence agents of the Colony Marshal Buero. You're probably under arrest if you see this.
  components:
  - type: Sprite
    sprite: _RMC14/Objects/CMIDs/general.rsi
    state: general
  - type: Clothing
    slots:
    - idcard
    sprite: _RMC14/Objects/CMIDs/general.rsi
  - type: PresetIdCard
    name: "CMB Informant ID Card"

- type: entity
  parent: CMIDCardLanyard
  id: RMCIDCardCMBInformantFakeID
  name: colonist ID card
  components:
  - type: PresetIdCard
    job: CMSurvivor
  - type: ItemIFF
    faction: FactionSurvivor

- type: entity
  parent: CMSatchel
  id: RMCSatchelCMBInformantFill
  suffix: Informant, Filled
  components:
  - type: StorageFill
    contents:
    - id: CMClipboard
    - id: RMCIDCardCMBInformant
    - id: CMPenFountain
    - id: CMSheetMetal20
    - id: CMWeaponPistolM1984
    - id: CMMagazinePistolM1984
