- type: job
  parent: CMJobBase
  id: RMCMarineInformant
  name: "UNMC Informant"
  description: "You are a informant for the United Nations Marine Corp. Report on anything relevant to your superiors via fax."
  playTimeTracker: RMCJobMarineInformant
  ranks:
    RMCRankCivilian: []
  startingGear: RMCGearMarineInformant
  icon: "RMCJobIconEmpty"
  joinNotifyCrew: false
  supervisors: "UNMC High Command"
  accessGroups:
  - Colonist
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillConstruction: 1
        RMCSkillEndurance: 2
        RMCSkillFireman: 1
        RMCSkillFirearms: 1
    - type: EquipSurvivorPreset
      preset: RMCSurvivorPresetInformant
    - type: RMCSurvivor
    - type: MotionDetectorTracked
    - type: NpcFactionMember
      factions:
      - Survivor
    - type: IntelRescueSurvivorObjective
  greeting: "You are a undercover operative for the United Nations Marine Corp. Report on happenings in the are via fax to high command."
  hasIcon: false
  hidden: true

- type: startingGear
  id: RMCGearMarineInformant
  equipment:
    jumpsuit: CMJumpsuitColonist
    back: RMCSatchelCivilianFill
    shoes: RMCShoesBlack
    id: RMCIDCardMarineInformant
    ears: CMHeadsetColony
    pocket1: RMCPouchSurvivalFill
    pocket2: RMCPouchGeneral
  inhand:
    - CMPenFountain
    - RMCIDCardInformantFakeID

- type: entity
  id: RMCRandomHumanoidUNMCInformant
  name: UNMC informant ghost role
  suffix: Spawner, Player, Informant
  components:
  - type: Sprite
    sprite: _RMC14/Structures/Machines/fax_machine.rsi
    state: icon
  - type: RandomHumanoidSpawner
    settings: RMCUNMCInformant

- type: randomHumanoidSettings
  parent: RMCEventHumanoid
  id: RMCUNMCInformant
  components:
  - type: GhostRole
    name: "UNMC Informant"
    description: "You are covert intelligence agent, sent from High Command. Report any happenings in the area via fax to your superiors. High Command will probably have a specific mission in mind..."
    rules: "Listen to the game master! Do not assume you are hostile to the marines. You do not remember anything from your previous life, etc."
    reregister: false
    job: RMCMarineInformant
    raffle:
      settings: short
  - type: GhostRoleApplySpecial

- type: entity
  parent: CMIDCardSilver
  id: RMCIDCardMarineInformant
  name: "Marine Informant ID card"
  description: A inconspicous ID card, issued to the covert intelligence agents of the UNMC. You probably dont have the clearance to see this.
  components:
  - type: Sprite
    sprite: _RMC14/Objects/CMIDs/silver_id.rsi
  - type: Clothing
    slots:
    - idcard
    sprite: _RMC14/Objects/CMIDs/silver_id.rsi
  - type: PresetIdCard
    job: RMCJobMarineInformant

- type: entity
  parent: CMIDCardLanyard
  id: RMCIDCardInformantFakeID
  name: colonist ID card
  components:
  - type: PresetIdCard
    job: CMSurvivor
  - type: ItemIFF
    faction: FactionSurvivor

- type: entity
  id: RMCSurvivorPresetInformant
  name: informant survivor preset
  components:
  - type: SurvivorPreset
    randomGear:
    - [ CMClipboard ]
    randomWeapon:
    - [ RMCWeaponPistolB92FS, RMCMagazinePistolB92FS ]
    - [ RMCWeaponRevolverSpearhead, RMCSpeedLoader357Hollowpoint ]
    - [ RMCWeaponPistolMK45, RMCMagazinePistolMK45 ]
    - [ CMWeaponPistolM1984, CMMagazinePistolM1984 ]
    # TODO RMC14 S&W .38 model 37 revolver
    primaryWeapons:
    - [ CMBeltMarineHunting, RMCWeaponBoltActionRifle ]
    #    - [ CMBeltMarineHunting, RMCWeaponBoltActionRifle ] # TODO RMC14 uzi
    - [ CMBeltMarineBuckshot, RMCWeaponShotgunHG3712 ]
    - [ CMBeltMarineAR10, WeaponRifleAR10 ]
    primaryWeaponChance: 0.6

- type: playTimeTracker
  id: RMCJobMarineInformant
