- type: entity
  id: RMCRandomHumanoidUNMCInformant
  name: UNMC Informant
  suffix: Spawner, Informant
  components:
  - type: Sprite
    sprite: _RMC14/Structures/Machines/fax_machine.rsi
    state: icon
  - type: RandomHumanoidSpawner
    settings: RMCUNMCInformantSettings

- type: randomHumanoidSettings
  parent: RMCEventHumanoid
  id: RMCUNMCInformantSettings
  components:
  - type: Rank
    rank: RMCRankCivilian
  - type: Loadout
    prototypes: [ RMCGearUNMCInformant  ]
  - type: GhostRole
    name: "UNMC Informant"
    description: "You are a informant for UNMC High Command. Relay any happenings in the area to them via fax. Try not to let the public know. The GM probably has a specific job in mind..."
    rules: "You do not remember your previous life. You are NOT hostile to any faction unless directed to be by the GM or a admin. Try to blend in, and behave as a civilian colonist would."
    reregister: false
    raffle:
      settings: short
  - type: GhostRoleApplySpecial
  - type: Skills
    skills:
      RMCSkillConstruction: 1
      RMCSkillEndurance: 2
      RMCSkillFireman: 1
      RMCSkillFirearms: 1

- type: startingGear
  id: RMCGearUNMCInformant
  equipment:
    jumpsuit: CMJumpsuitColonist
    back: RMCSatchelUNMCInformantFill
    shoes: RMCShoesBlack
    id: RMCIDCardInformantFakeID
    ears: CMHeadsetColony
    pocket1: RMCPouchSurvivalFill
    pocket2: RMCPouchGeneral

- type: entity
  parent: CMIDCardGold
  id: RMCIDCardMarineInformant
  name: "UNMC Informant ID card"
  description: A shiny ID card, issued to the covert intelligence agents of the UNMC. You probably dont have the clearance to see this.
  components:
  - type: Sprite
    sprite: _RMC14/Objects/CMIDs/general.rsi
    state: general
  - type: Clothing
    slots:
    - idcard
    sprite: _RMC14/Objects/CMIDs/general.rsi
  - type: PresetIdCard
    name: "UNMC Informant ID Card"

- type: entity
  parent: CMIDCardLanyard
  id: RMCIDCardInformantFakeID
  name: colonist ID card
  components:
  - type: PresetIdCard
    job: CMSurvivor
  - type: ItemIFF
    faction: FactionSurvivor

- type: entity
  parent: CMSatchel
  id: RMCSatchelUNMCInformantFill
  suffix: Informant, Filled
  components:
  - type: StorageFill
    contents:
    - id: CMClipboard
    - id: RMCIDCardMarineInformant
    - id: CMPenFountain
    - id: CMSheetMetal20
    - id: CMWeaponPistolM1984
    - id: CMMagazinePistolM1984
