- type: job
  parent: RMCJobRibbonBase
  id: CMWeYaresponder
  name: rmc-job-name-weya-responder
  description: rmc-job-description-weya-responder
  playTimeTracker: CMJobWeYaResponder
>>>>>>> ab2d3a0c72a90f03cf68ad3770fbe024e1b1c30a
  ranks:
    RMCRankWeYaExecutiveSpecialist: []
  startingGear: RMCGearWeYaResponder
  icon: "CMJobIconEmpty"
  joinNotifyCrew: false
<<<<<<< HEAD
=======
  supervisors: cm-job-supervisors-staff
>>>>>>> ab2d3a0c72a90f03cf68ad3770fbe024e1b1c30a
  accessGroups:
  - ShipMasterAccess
  spawnMenuRoleName: WEYA Communications Executive
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - WeYa
    - type: Skills
      skills:
        RMCSkillConstruction: 2
        RMCSkillEngineer: 2
        RMCSkillFirearms: 1
        RMCSkillFireman: 1
        RMCSkillIntel: 1
        RMCSkillJtac: 3
        RMCSkillMedical: 2
        RMCSkillOverwatch: 1
        RMCSkillPolice: 1
        RMCSkillPowerLoader: 1
        RMCSkillSurgery: 1
        RMCSkillVehicles: 2
    - type: RMCRibbon
  hasIcon: false
  hidden: true

>>>>>>> ab2d3a0c72a90f03cf68ad3770fbe024e1b1c30a
- type: startingGear
  id: RMCGearWeYaResponder
  equipment:
    ears: RMCHeadsetDistressPMCDirector
    back: CMSatchel
<<<<<<< HEAD
=======
    belt: CMClipboard
>>>>>>> ab2d3a0c72a90f03cf68ad3770fbe024e1b1c30a
    head: ArmorHelmetPMC
    jumpsuit: CMJumpsuitLiaisonBlack
    outerClothing: RMCJacketCorporateFormal
    shoes: RMCShoesLaceup
    id: RMCIDCardWeYaResponder
    pocket1: RMCPouchGeneralLarge
    pocket2: RMCPouchDocument

- type: entity
  parent: CMIDCardGold
  id: RMCIDCardWeYaResponder
  name: We-Ya Communications Executive ID card
  description: A fancy, faux gold plated ID card. One of many given to Weston-Yamada's army of fax operators.
  components:
  - type: Sprite
    sprite: _RMC14/Objects/CMIDs/gold_id.rsi
  - type: Clothing
    slots:
    - idcard
    sprite: _RMC14/Objects/CMIDs/gold_id.rsi
  - type: PresetIdCard
<<<<<<< HEAD
    job: RMCWeYaResponder

- type: playTimeTracker
  id: RMCJobWeYaResponder
=======
    job: CMWeYaresponder

- type: playTimeTracker
  id: CMJobWeYaResponder
>>>>>>> ab2d3a0c72a90f03cf68ad3770fbe024e1b1c30a
